<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrackMatch.Application\TrackMatch.Application.csproj" />
    <ProjectReference Include="..\TrackMatch.Core\TrackMatch.Core.csproj" />
    <ProjectReference Include="..\TrackMatch.Infrastructure\TrackMatch.Infrastructure.csproj" />
  </ItemGroup>

</Project>
