<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TrackMatch.Core\TrackMatch.Core.csproj" />
    <ProjectReference Include="..\TrackMatch.Infrastructure\TrackMatch.Infrastructure.csproj" />
  </ItemGroup>
</Project>
